export const genres = [
  { title: "Pop", value: "POP" },
  { title: "Hip-Hop", value: "HIP-HOP-RAP" },
  { title: "Dance", value: "DANCE" },
  { title: "Electronic", value: "ELECTRONIC" },
  { title: "Alternative", value: "ALTERNATIVE" },
  { title: "Native", value: "NATIVE" },
  { title: "Country", value: "COUNTRY" },
  { title: "Worldwide", value: "WORLDWIDE" },
  { title: "House", value: "HOUSE" },
  { title: "Latin", value: "LATIN" },
  { title: "Rock", value: "ROCK" },
  { title: "Reggae", value: "REGGAE_DANCE_HALL" },
  { title: "K-pop", value: "K_POP" },
  { title: "Film-tv", value: "FILM_TV" },
];
